version: '3'

networks:
  frontend:
  backend:

services:

  nginx:
    image: nginx
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
#    volumes:
#      - "~/Desktop/inception/website:/var/www/html"
    depends_on:
      - wordpress
    restart: always
    networks:
      - frontend

  mariadb:
    image: mariadb
    container_name: mariadb
    build: requirements/mariadb
    ports:
      - "3306:3306"
    restart: always
    networks:
      - backend
    environment:
      DB_NAME: ${DB_NAME}
      DB_ROOT: ${DB_ROOT}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

  wordpress:
    image: wordpress
    container_name: wordpress
    build: requirements/wordpress/
    ports:
      - "9000:9000"
    restart: always
    networks:
      - frontend
      - backend
    depends_on:
      - mariadb
    environment:
      DB_NAME: ${DB_NAME}
      DB_ROOT: ${DB_ROOT}
      DB_HOST_NAME: ${DB_HOST_NAME}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_USER_PASSWORD: ${WP_ADMIN_USER_PASSWORD}
      WP_USER: ${WP_USER}
      WP_USER_PASSWORD: ${WP_USER_PASSWORD}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_ADMIN_USER_EMAIL: ${WP_ADMIN_USER_EMAIL}
      WP_TITLE: ${WP_TITLE}

